<a href="https://colab.research.google.com/github/akshara2207/DS-ML/blob/main/DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("Example for broadcasting: ")
v=np.array([1,2,3])
w=np.array([4,5])
print("v = ",v)
print("w=",w)
print("Outer product of above vectors: ")
print(np.reshape(v,(3,1))*w)
x=np.array([[1,2,3],[4,5,6]])
print("x = ",x)
print("Resultant matrix after adding the vector x to each row of matrix v: ")
print(x+v)
print("Example for broadcasting fails: ")
print("Adding the vector x to each column of matrix w will generate an error")
print("Solution: Reshape the matrix w then the result will be: ")
print(x+np.reshape(w,(2,1)))

Example for broadcasting: 
v =  [1 2 3]
w= [4 5]
Outer product of above vectors: 
[[ 4  5]
 [ 8 10]
 [12 15]]
x =  [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector x to each row of matrix v: 
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails: 
Adding the vector x to each column of matrix w will generate an error
Solution: Reshape the matrix w then the result will be: 
[[ 5  6  7]
 [ 9 10 11]]


In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[6, 9], [4, 4]], dtype=np.float64)

print("Element wise addition:", np.add(x, x))
print("x =", x)
print("y =", y)
print("Element wise subtraction:", np.subtract(x, y))
print("Element wise multiplication:", np.multiply(x, y))
print("Element wise square root of x:", np.sqrt(x))
print("Matrix multiplication:", np.dot(x, y))
print("Sum of all elements of matrix x:", np.sum(x))
print("Sum of elements in each column of matrix y:", np.sum(y, axis=0))
print("Sum of elements in each row of matrix y:", np.sum(y, axis=1))
print("Transpose of matrix x:", x.T)

Element wise addition: [[2. 4.]
 [6. 8.]]
x = [[1. 2.]
 [3. 4.]]
y = [[6. 9.]
 [4. 4.]]
Element wise subtraction: [[-5. -7.]
 [-1.  0.]]
Element wise multiplication: [[ 6. 18.]
 [12. 16.]]
Element wise square root of x: [[1.         1.41421356]
 [1.73205081 2.        ]]
Matrix multiplication: [[14. 17.]
 [34. 43.]]
Sum of all elements of matrix x: 10.0
Sum of elements in each column of matrix y: [10. 13.]
Sum of elements in each row of matrix y: [15.  8.]
Transpose of matrix x: [[1. 3.]
 [2. 4.]]
